import {IMultiSelectOption} from 'angular-2-dropdown-multiselect';

export const fields: object[] = [
  {name: 'department', id: 0, type: 'text'},
  {name: 'command', id: 1, type: 'text'},
  {name: 'middleName', id: 2, type: 'text'},
  {name: 'suffix', id: 3, type: 'text'},
  {name: 'age', id: 4, type: 'text'},
  {name: 'ethnicity', id: 5, type: 'text'},
  {name: 'religiousPreference', id: 6, type: 'text'},
  {name: 'supervisor', id: 7, type: 'text'},
  {name: 'workCenter', id: 8, type: 'text'},
  {name: 'workRoom', id: 9, type: 'text'},
  {name: 'shift', id: 10, type: 'text'},
  {name: 'jobTitle', id: 11, type: 'text'},
  {name: 'eaos', id: 12, type: 'date'},
  {name: 'prd', id: 13, type: 'date'},
  {name: 'dateOfDeparture', id: 14, type: 'date'},
  {name: 'billetAssignment', id: 15, type: 'text'},
  {name: 'paygrade', id: 16, type: 'text'},
  {name: 'designation', id: 17, type: 'text'},
  {name: 'uic', id: 18, type: 'text'},
  {name: 'dutyStatus', id: 19, type: 'text'},
  {name: 'sex', id: 20, type: 'sex'},
  {name: 'lastName', id: 21, type: 'text'},
  {name: 'firstName', id: 22, type: 'text'},
  {name: 'doDId', id: 23, type: 'text'},
  {name: 'dateOfBirth', id: 24, type: 'date'},
  {name: 'dateOfArrival', id: 25, type: 'date'},
  {name: 'division', id: 26, type: 'text'},
];
